name="matrix"
tagline="The classic digital rain."
description="A matrix-style screensaver with falling green characters. This version is optimized for speed."
authors="attogram"
license="MIT"
settings=""
