name="pipes"
tagline="A classic, endless maze of pipes."
description="An animated pipes terminal screensaver. This is a classic, highly customizable screensaver."
authors="Pipeseroni/pipes.sh contributors, Yu-Jie Lin, Matthew Simpson"
license="MIT"
settings="-p [1-], -t [0-9], -c [0-7], -f [20-100], -s [5-15], -r [0-], -R, -B, -C, -K"
